import assert from 'node:assert/strict';
import { archiveStructuralSpans } from '../../../src/integrations/inference-history/archive-structure.js';
import { digest, DEFAULT_LIMITS } from '../../../src/integrations/inference-history/common.js';
import { ARTIFACT_PROJECTION_VERSION, projectArtifact, sanitizeArtifactJson } from '../../../src/integrations/inference-history/artifact-projection.js';
import { normalizeHistoryRecord } from '../../../src/integrations/inference-history/records.js';
import { sanitizeEmbeddedAssetText } from '../../../src/integrations/inference-history/embedded-assets.js';
const payload = Buffer.from('binary asset bytes '.repeat(40)).toString('base64');
const audit = {};
const source = { image: 'data:image/png;base64,' + payload, nested: { image_base64: payload }, ordinary_code: payload,
  prose: 'before data:application/octet-stream;base64,' + payload + ' after', password: 'secret' };
const sanitized = sanitizeArtifactJson(source, 0, { audit });
assert.equal(sanitized.image.embedded_asset_omitted.media_type, 'image/png');
assert.equal(sanitized.image.embedded_asset_omitted.payload_sha256, digest(payload));
assert.equal(sanitized.nested.image_base64.embedded_asset_omitted.encoded_chars, payload.length);
assert.equal(sanitized.ordinary_code, payload);
assert.ok(sanitized.prose.startsWith('before ')); assert.ok(sanitized.prose.endsWith(' after'));
assert.ok(!sanitized.prose.includes(payload)); assert.equal(Object.hasOwn(sanitized, 'password'), false);
assert.equal(audit.embeddedAssetPayloads, 3); assert.equal(audit.embeddedAssetEncodedChars, payload.length * 3);
assert.deepEqual(sanitizeArtifactJson(sanitized), sanitized);
const rawCode = 'const image = "data:image/png;base64,' + payload + '";\nfunction useAsset(){return image;}';
const records = projectArtifact({ text: rawCode, sourceSha256: 'a'.repeat(64), locator: 'assets.js', kind: 'code' });
const reconstructed = records.map(row => row.body).join('');
assert.ok(!reconstructed.includes(payload)); assert.ok(reconstructed.includes('function useAsset'));
assert.ok(reconstructed.includes('";\nfunction'));
assert.equal(records[0].provenance.projection_version, ARTIFACT_PROJECTION_VERSION);
assert.equal(records[0].provenance.transformation.original_end, rawCode.length);
assert.equal(normalizeHistoryRecord(records[0], 'recovered_artifact', DEFAULT_LIMITS).nodes[0].sourceDetails.projectionVersion, ARTIFACT_PROJECTION_VERSION);
assert.equal(sanitizeEmbeddedAssetText('ordinaryBase64 = ' + payload), 'ordinaryBase64 = ' + payload);
assert.equal(sanitizeEmbeddedAssetText('data:image/png,not-base64-data'), 'data:image/png,not-base64-data');
assert.equal(source.image, 'data:image/png;base64,' + payload);
console.log('narrow embedded asset payload omission preserves surrounding source, facts, original identity and audit counts');

assert.doesNotThrow(() => new Function(reconstructed));
const codeWithFunctions = '/** first asset consumer */\nfunction first(){ const asset = "data:image/png;base64,' + payload + '"; return asset; }\n\n/** second consumer */\nfunction second(){return 2;}';
const codeRecords = projectArtifact({ text: codeWithFunctions, sourceSha256: 'a'.repeat(64), locator: 'consumers.js', kind: 'code' });
const safeCode = codeRecords.map(row => row.body).join('');
assert.doesNotThrow(() => new Function(safeCode));
const safeSpans = archiveStructuralSpans(safeCode, { locator: 'consumers.js', kind: 'code', chunkChars: 1000, overlapChars: 200 });
assert.equal(safeSpans.length, 2); assert.ok(safeSpans[0].title.includes('first')); assert.ok(safeSpans[1].title.includes('second'));
assert.ok(safeSpans[0].text.includes('first asset consumer')); assert.ok(safeSpans[1].text.includes('second consumer'));
assert.equal(safeSpans.map(row => row.text).join(''), safeCode);
