import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { makeTempDir } from '../../helpers/temp.js';
import { digest } from '../../../src/integrations/inference-history/common.js';
import { projectArtifact } from '../../../src/integrations/inference-history/artifact-projection.js';
import { createInferenceHistoryService, createLocalSourceHistoryService } from '../../../src/integrations/inference-history/service.js';
import { createHistoryAgentBroker } from '../../../src/integrations/inference-history/agent-broker.js';
import { createHistoryOwnerConsole } from '../../../src/integrations/inference-history/owner-console.js';
import { createHistoryAgentReader } from '../../../src/integrations/inference-history/agent-reader.js';
import { createHistoryAuditLedger } from '../../../src/integrations/inference-history/audit.js';
import { createHistoryOwnerHttpHandler } from '../../../src/integrations/inference-history/owner-http.js';

const root=await fs.realpath(await makeTempDir('local-source-history-'));
const source=path.join(root,'artifacts-0001.json');
await fs.writeFile(source,JSON.stringify(projectArtifact({text:'synthetic cobalt artifact',sourceSha256:'a'.repeat(64),locator:'fixture.txt'})));
const bytes=await fs.readFile(source),before=await fs.readdir(root),sourceMode=(await fs.stat(source)).mode;
const options={sources:[{path:source,sha256:digest(bytes)}]};
await assert.rejects(createLocalSourceHistoryService({...options,maxSourceBytes:1}),{code:'ERR_INFERENCE_HISTORY_LIMIT'});
await assert.rejects(createLocalSourceHistoryService({...options,sources:[{path:source,sha256:'b'.repeat(64)}]}),{code:'ERR_INFERENCE_HISTORY_INPUT'});
await assert.rejects(createLocalSourceHistoryService({sources:[{path:'../escape.json',sha256:digest(bytes)}]}),{code:'ERR_INFERENCE_HISTORY_INPUT'});
await assert.rejects(createLocalSourceHistoryService({...options,resolveAccess:()=>true}),{code:'ERR_INFERENCE_HISTORY_INPUT'});
const local=await createLocalSourceHistoryService(options);
const result=await local.search({query:'cobalt',role:'artifact'});
assert.equal(result.totalMatches,1);
assert.equal(result.localSource.audit,'disabled');
assert.equal(result.localSource.filesystemIndexWrites,false);
assert.equal(result.localSource.storage,'memory_only');
for(const action of ['importExport','deleteRecord','ownerSetPrivacy','ownerInventory'])assert.equal(local[action],undefined);
assert.throws(()=>createHistoryAgentBroker({service:local,boundary:{bind(){}}}),/authenticated/);
assert.throws(()=>createHistoryAgentBroker({service:{...local},boundary:{bind(){}}}),/authenticated/);
assert.throws(()=>createHistoryOwnerConsole({service:local,authenticateHuman:()=>{},auditLedger:{}}),/owner host/);
const reader=createHistoryAgentReader({service:local});
const packet=await reader.execute('search',{query:'cobalt'});
assert.equal(packet.ok,true);assert.equal(packet.page.totalMatches,1);
await local.dispose();await assert.rejects(local.search({query:'cobalt'}),{code:'ERR_INFERENCE_HISTORY_DENIED'});
assert.deepEqual(await fs.readdir(root),before);
assert.deepEqual(await fs.readFile(source),bytes);
assert.equal((await fs.stat(source)).mode,sourceMode);
for(const audit of [()=>({persisted:false}),()=>{throw Error('optional log unavailable');}]){
  const logged=await createLocalSourceHistoryService({...options,audit});
  assert.equal((await logged.search({query:'cobalt'})).totalMatches,1);
  assert.equal(logged.localSource.audit,'optional_callback');await logged.dispose();
}
console.log('selected local reads without host/audit/ACL prerequisites, optional log failures, source preservation and transport guards passed');

const access={principalId:'fixture',tenantId:'fixture',ownerType:'individual',ownerId:'fixture',sourceScope:'synthetic',policyEpoch:'1',allowed:true};
assert.throws(()=>createInferenceHistoryService({resolveAccess:()=>access}),{code:'ERR_INFERENCE_HISTORY_AUDIT'});
assert.throws(()=>createInferenceHistoryService({resolveAccess:()=>access,audit:()=>({persisted:true}),localSourceToken:'local'}),{code:'ERR_INFERENCE_HISTORY_DENIED'});
assert.throws(()=>createHistoryAgentReader({service:{search(){}}}),/partition/);
const broadVault=path.join(root,'synthetic-broad-vault');await fs.mkdir(broadVault,{mode:0o755});
const strict=createInferenceHistoryService({vaultRoot:broadVault,resolveAccess:()=>access,audit:()=>({persisted:true}),verifyPrivateVault:()=>false});
await assert.rejects(strict.search({requestContext:'fixture',partition:'own',query:'cobalt'}),{code:'ERR_INFERENCE_HISTORY_STORAGE'});
const ledger=createHistoryAuditLedger({auditRoot:broadVault,verifyPrivateVault:()=>false});
await assert.rejects(ledger.append({action:'synthetic'}),{code:'ERR_INFERENCE_HISTORY_STORAGE'});
assert.deepEqual(await fs.readdir(broadVault),[]);
assert.throws(()=>createHistoryOwnerHttpHandler({console:{executionContext:'local_source_readonly',page(){},audit(){},setPrivacy(){}},boundary:{bind(){}},origin:'https://fixture.invalid'}),/trusted owner/);
await assert.rejects(createLocalSourceHistoryService({...options,maxUnits:0}),{code:'ERR_INFERENCE_HISTORY_INPUT'});
const manyPath=path.join(root,'artifacts-0002.json'),manyBytes=Buffer.from(JSON.stringify(projectArtifact({text:'bounded artifact '.repeat(1000),sourceSha256:'c'.repeat(64),locator:'many.txt'})));
await fs.writeFile(manyPath,manyBytes);
await assert.rejects(createLocalSourceHistoryService({...options,sources:[{path:manyPath,sha256:digest(manyBytes)}],maxUnits:1}),{code:'ERR_INFERENCE_HISTORY_LIMIT'});
console.log('service audit/storage/authentication guards and local corpus limits remain enforced');
