import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { digest } from '../../../src/integrations/inference-history/common.js';
import { projectArtifact } from '../../../src/integrations/inference-history/artifact-projection.js';
import { createLocalSourceHistoryService } from '../../../src/integrations/inference-history/service.js';
import { createHistoryAgentReader } from '../../../src/integrations/inference-history/agent-reader.js';
const base=process.env.PAIROFCLEATS_ARCHIVE_DISCOVERY_TEST_DIR || path.join(process.cwd(),'temp','tasks','archive-discovery-tests');
await fs.mkdir(base,{recursive:true});
const root=await fs.realpath(await fs.mkdtemp(path.join(base,'fixture-')));
const source=path.join(root,'artifacts-0001.json');
const conversations=path.join(root,'conversations-0001.json');
const artifact=projectArtifact({text:'neutral '.repeat(1000),sourceSha256:'a'.repeat(64),locator:'project/manual-aurora.txt',kind:'code',chunkChars:1000});
const message=(id,parent,role,text)=>({id,parent,message:{id:'m-'+id,author:{role},create_time:1770000000,content:{content_type:'text',parts:[text]}}});
const conversation={id:'dialog',title:'distinctive nebula title',current_node:'assistant',mapping:{user:message('user',null,'user','Please explain cobalt'),assistant:message('assistant','user','assistant','Cobalt is an example'),alternate:message('alternate','user','user','Offbranch text')}};
await fs.writeFile(source,JSON.stringify(artifact));
await fs.writeFile(conversations,JSON.stringify([conversation]));
const options={sources:[{path:source,sha256:digest(await fs.readFile(source))},{path:conversations,sha256:digest(await fs.readFile(conversations))}],indexPath:path.join(root,'collection.sqlite')};
let service=await createLocalSourceHistoryService(options);
const reader=createHistoryAgentReader({service});
assert.equal((await service.search({query:'nebula'})).totalMatches,0,'body search remains literal body evidence');
const title=await reader.execute('search',{query:'nebula',searchField:'title'});
assert.equal(title.ok,true);assert.ok(title.evidence.length>0,'agent native title discovery');
const paths=await service.search({query:'aurora',searchField:'path',groupBy:'original'});
assert.equal(paths.totalMatches,1,'multiple chunks of one preserved source group as one original');
assert.ok(paths.hits[0].groupCount>1);
const facets=await service.search({query:'code',searchField:'facets',role:'artifact',groupBy:'original'});
assert.equal(facets.totalMatches,1,'native artifact kind facet discovery');
const assistant=(await service.search({query:'cobalt',role:'assistant'})).hits[0];
const context=await service.readContext({sourceRef:assistant.sourceRef,snapshotRef:assistant.snapshotRef,preset:'user'});
assert.ok(context.messages.length>0);assert.ok(context.messages.every(m=>m.role==='user'));
assert.ok(context.messages.every(m=>!m.text.includes('Offbranch')),'context stays on anchor ancestry');
const reference=paths.hits[0].sourceRef,snapshot=paths.hits[0].snapshotRef;
await service.dispose();
service=await createLocalSourceHistoryService({...options,rebuildDiscovery:true});
const reloaded=(await service.search({query:'aurora',searchField:'path',groupBy:'original'})).hits[0];
assert.equal(reloaded.sourceRef,reference);assert.equal(reloaded.snapshotRef,snapshot,'explicit rebuild preserves citation identity');
await service.dispose();
console.log('native archive discovery, original grouping, role context and explicit rebuild identity passed');
