import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import Database from 'better-sqlite3';
import {makeTempDir} from '../../helpers/temp.js';
import {digest} from '../../../src/integrations/inference-history/common.js';
import {createLocalSourceHistoryService} from '../../../src/integrations/inference-history/service.js';
import {createHistoryAgentReader} from '../../../src/integrations/inference-history/agent-reader.js';
const root=await fs.realpath(await makeTempDir('archive-ranked-continuation-'));
const source=path.join(root,'conversations.json');
const conversation=(id,role,text)=>({id,title:id,current_node:'n',mapping:{n:{id:'n',parent:null,message:{id:'message-'+id,author:{role},create_time:1,content:{content_type:'text',parts:[text]}}}}});
const rows=Array.from({length:1000},(_,i)=>conversation('assistant-'+i,'assistant','cobalt '+ 'padding '.repeat(30)));
rows.push(...Array.from({length:1000},(_,i)=>conversation('user-'+i,'user','cobalt '+ 'padding '.repeat(30))));
rows.push(conversation('strongest-last-user','user','cobalt '.repeat(50)));
rows.push(conversation('exact-exclusion-survivor','user','cobalt valid survivor'));
await fs.writeFile(source,JSON.stringify(rows));
const options={sources:[{path:source,sha256:digest(await fs.readFile(source))}],indexPath:path.join(root,'archive.sqlite')};
let service=await createLocalSourceHistoryService(options);
const first=await service.search({query:'cobalt',role:'user',top:100});
assert.equal(first.hits[0].title,'strongest-last-user');assert.equal(first.complete,false);
assert.equal(first.totalMatches,null);assert.ok(first.continuation);
first.coverage.records=0;
assert.equal((await service.search({query:'cobalt',role:'user',top:1})).coverage.records,2002);
const excluded=await service.search({query:'cobalt -padding',role:'user',top:100});
assert.equal(excluded.totalMatches,2);assert.equal(excluded.complete,true);
assert.ok(excluded.hits.some(hit=>hit.title==='exact-exclusion-survivor'));
const reader=createHistoryAgentReader({service});
const tail=await reader.execute('search',{query:'cobalt',role:'user',top:100,offset:900},{maxOutputBytes:2097152});
assert.equal(tail.ok,true);assert.ok(tail.page.next.request.continuation);
const continuation=tail.page.next;
const next=await reader.execute(continuation.command,continuation.request);
assert.equal(next.ok,true);assert.equal(next.evidence.length,2);assert.equal(next.page.next,null);
assert.equal(next.result,undefined);
await assert.rejects(service.search({...continuation.request,query:'padding'}),{code:'ERR_INFERENCE_HISTORY_INPUT'});
await service.dispose();
service=await createLocalSourceHistoryService(options);
assert.equal((await createHistoryAgentReader({service}).execute(continuation.command,continuation.request)).ok,true);
await service.dispose();
const db=new Database(options.indexPath);db.prepare("UPDATE vault_meta SET value=CAST(value AS INTEGER)+1 WHERE key='generation'").run();db.close();
service=await createLocalSourceHistoryService(options);
await assert.rejects(service.search(continuation.request),{code:'ERR_INFERENCE_HISTORY_STALE'});
await service.dispose();
console.log('Archive role/relevance before cap, continuation beyond 1000, query/generation binding, reload and immutable generation coverage passed');
