import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { projectArtifact, sanitizeArtifactJson } from '../../../src/integrations/inference-history/artifact-projection.js';
import { classifyBinaryEvidence } from '../../../src/integrations/inference-history/file-evidence-recovery.js';
import { normalizeHistoryRecord } from '../../../src/integrations/inference-history/records.js';
import { DEFAULT_LIMITS } from '../../../src/integrations/inference-history/common.js';
import { createInferenceHistoryService } from '../../../src/integrations/inference-history/service.js';
import { makeTempDir } from '../../helpers/temp.js';
const hash = 'a'.repeat(64);
assert.equal(projectArtifact({text:'<analysis>hidden</analysis>',sourceSha256:hash}).length,0);
const safe = sanitizeArtifactJson({password:'secret',messages:[{channel:'analysis',body:'hidden'}],code:'visible cobalt'});
assert.deepEqual(safe,{code:'visible cobalt'});
const records=projectArtifact({text:'visible cobalt '.repeat(600),sourceSha256:hash,locator:'fixture/code.js',kind:'code'});
assert.ok(records.length>1);
for(const record of records)assert.equal(normalizeHistoryRecord(record,'recovered_artifact',DEFAULT_LIMITS).nodes[0].role,'artifact');
assert.throws(()=>normalizeHistoryRecord({...records[0],provenance:{source_sha256:hash,raw:'hidden'}},'recovered_artifact',DEFAULT_LIMITS));
assert.throws(()=>normalizeHistoryRecord({...records[0],body:'{"channel":"analysis"}'},'recovered_artifact',DEFAULT_LIMITS));
const mesh=Buffer.alloc(134);mesh.writeUInt32LE(1,80);mesh.writeFloatLE(2,96);
assert.equal(classifyBinaryEvidence(mesh).metadata.triangles,1);
assert.equal(classifyBinaryEvidence(mesh.subarray(0,133)).status,'unresolved_schema');
const root=await fs.realpath(await makeTempDir('recovered-artifact-'));
const vaultRoot=path.join(root,'vault'),sourcePath=path.join(root,'artifacts-0001.json');
await fs.mkdir(vaultRoot,{mode:0o700});await fs.writeFile(sourcePath,JSON.stringify(records));
const request={requestContext:'synthetic',partition:'own'};
const access={principalId:'fixture',tenantId:'fixture',ownerType:'individual',ownerId:'fixture',sourceScope:'synthetic',policyEpoch:'1',allowed:true};
const service=createInferenceHistoryService({vaultRoot,audit:()=>({persisted:true}),verifyPrivateVault:()=>true,
  resolveAccess:()=>access,resolveImportSource:()=>({path:sourcePath,policyEpoch:'1'})});
await service.importExport(request);
const result=await service.search({...request,query:'cobalt',role:'artifact'});
assert.ok(result.totalMatches>0);
console.log('recovered artifact projection/import/search and binary bounds passed');

const { extractFileEvidence }=await import('../../../src/integrations/inference-history/file-evidence.js');
const { recoverFileEvidenceGaps }=await import('../../../src/integrations/inference-history/file-evidence-recovery.js');
const { prepareFileEvidenceArtifacts }=await import('../../../src/integrations/inference-history/artifact-preparation.js');
const { default: Database }=await import('better-sqlite3');
const sources=path.join(root,'sources'),catalogRoot=path.join(root,'catalog');
await fs.mkdir(sources);await fs.writeFile(path.join(sources,'broken.dat'),'[section]\nkey=value\n');
await fs.writeFile(path.join(sources,'valid.dat'),'{"repo":"synthetic","commit":"'+'b'.repeat(40)+'"}');
const extraction=await extractFileEvidence({sourceRoot:sources,outputRoot:catalogRoot,authorizePaths:()=>true});
const db=new Database(extraction.catalogPath);
db.prepare("UPDATE documents SET status='facts_limited' WHERE format='json' AND status='supported'").run();db.close();
await assert.rejects(recoverFileEvidenceGaps({catalogPath:extraction.catalogPath}),/authorization/);
const recovery=await recoverFileEvidenceGaps({catalogPath:extraction.catalogPath,authorizeCatalog:()=>true});
assert.equal(recovery.factIndexes[0].status,'complete');
assert.ok(recovery.formats.some(item=>item.format==='ini'));
const prepared=await prepareFileEvidenceArtifacts({catalogPaths:[extraction.catalogPath],outputRoot:path.join(root,'prepared'),authorizePaths:()=>true});
assert.equal(prepared.activation,'not_imported');assert.ok(prepared.records>0);
console.log('gap overlay preserves originals; bounded fact completion and preparation passed');

const {decodeObfuscatedFont}=await import('../../../src/integrations/inference-history/file-evidence-recovery.js');
const font=Buffer.alloc(40);font.writeUInt32BE(0x10000,0);font.writeUInt16BE(1,4);font.write('test',12);font.writeUInt32BE(28,20);font.writeUInt32BE(12,24);
const fontKey='00112233-4455-6677-8899-aabbccddeeff',key=Buffer.from(fontKey.replaceAll('-',''),'hex').reverse(),obfuscated=Buffer.from(font);
for(let i=0;i<32;i++)obfuscated[i]^=key[i%16];
assert.deepEqual(decodeObfuscatedFont(obfuscated,fontKey).bytes,font);
assert.throws(()=>decodeObfuscatedFont(obfuscated,'invalid'),/key/);
