import assert from 'node:assert/strict';
import { createLocalHistorySemanticIndex } from '../../../src/integrations/inference-history/semantic-index.js';
const sourceRef='1'.repeat(64),snapshotRef='2'.repeat(64),generationRef='3'.repeat(64);
let permitted=true,calls=0;
const reauthorize=()=>{if(!permitted)throw Object.assign(new Error('synthetic revoked'),{code:'ERR_INFERENCE_HISTORY_DENIED'});};
const encodeText=text=>{calls++;return /cobalt|transport/i.test(text)?[1,0]:[0,1];};
const index=createLocalHistorySemanticIndex({modelId:'synthetic-toy',modelVersion:'1',dimensions:2,encodeText,chunkChars:80,overlapChars:20});
assert.throws(()=>index.adapter(),{code:'ERR_INFERENCE_HISTORY_UNAVAILABLE'});
const text='padding '.repeat(15)+'cobalt transport '+'tail '.repeat(20);
const documents=[{sourceRef,snapshotRef,text}];
const first=await index.refresh({documents,generationRef},{reauthorize});
assert.ok(first.spans>1);assert.equal(first.encoded,first.spans);assert.equal(first.reused,0);
const initialCalls=calls,adapter=index.adapter();
const result=await adapter.search({query:'transport precision',top:1,generationRef},{reauthorize});
assert.equal(result.candidates.length,1);assert.equal(result.complete,true);
const span=result.candidates[0].span;
assert.ok(text.slice(span.start,span.end).includes('cobalt'));
assert.equal(adapter.contentManifestHash,first.contentManifestHash);
const repeated=await index.refresh({documents,generationRef},{reauthorize});
assert.equal(repeated.encoded,0);assert.equal(repeated.reused,first.spans);assert.equal(calls,initialCalls+1);
assert.equal(first.contentManifestHash,repeated.contentManifestHash);
const nextGeneration='4'.repeat(64);
const changed=await index.refresh({documents:[{sourceRef,snapshotRef,text:text+'extra'}],generationRef:nextGeneration},{reauthorize});
assert.ok(changed.encoded>0);assert.ok(changed.reused>0);
assert.notEqual(changed.contentManifestHash,first.contentManifestHash);
assert.equal(index.adapter().indexGenerationRef,nextGeneration);
await assert.rejects(adapter.search({query:'transport',top:1,generationRef:nextGeneration},{reauthorize}),{code:'ERR_INFERENCE_HISTORY_STALE'});
permitted=false;
await assert.rejects(index.refresh({documents:[],generationRef},{reauthorize}),{code:'ERR_INFERENCE_HISTORY_DENIED'});
assert.equal(index.adapter().indexGenerationRef,nextGeneration);permitted=true;
const aborted=new AbortController();aborted.abort();
await assert.rejects(index.refresh({documents,generationRef},{reauthorize,signal:aborted.signal}));
assert.equal(index.adapter().indexGenerationRef,nextGeneration);
await assert.rejects(index.refresh({documents:[null],generationRef},{reauthorize}),{code:'ERR_INFERENCE_HISTORY_INPUT'});
const cleared=await index.refresh({documents:[],generationRef},{reauthorize});
assert.equal(cleared.spans,0);
assert.deepEqual((await index.adapter().search({query:'transport',top:10,generationRef},{reauthorize})).candidates,[]);
const bad=createLocalHistorySemanticIndex({modelId:'synthetic',modelVersion:'1',dimensions:2,encodeText:()=>[NaN,0]});
await assert.rejects(bad.refresh({documents,generationRef},{reauthorize}),{code:'ERR_INFERENCE_HISTORY_INPUT'});
assert.throws(()=>bad.adapter(),{code:'ERR_INFERENCE_HISTORY_UNAVAILABLE'});
const unicode=createLocalHistorySemanticIndex({modelId:'synthetic',modelVersion:'1',dimensions:2,encodeText,chunkChars:80,overlapChars:79});
const unicodeText='😀'.repeat(100);
const unicodeManifest=await unicode.refresh({documents:[{sourceRef,snapshotRef,text:unicodeText}],generationRef},{reauthorize});
assert.ok(unicodeManifest.spans<200);
const unicodeRows=await unicode.adapter().search({query:'other',top:100,generationRef},{reauthorize});
assert.ok(unicodeRows.candidates.every(row=>row.span.start%2===0&&row.span.end%2===0));
process.stdout.write('Synthetic incremental local semantic index, spans, revocation and Unicode bounds passed.\n');

let release;const blocked=createLocalHistorySemanticIndex({modelId:'synthetic',modelVersion:'1',dimensions:2,encodeText:(_text,options)=>options?.signal?new Promise(resolve=>{release=()=>resolve([1,0]);}):[1,0]});
const concurrentDocuments=[{sourceRef,snapshotRef,text:'original span'}];
const pending=blocked.refresh({documents:concurrentDocuments,generationRef},{reauthorize});
while(!release)await new Promise(resolve=>setImmediate(resolve));
concurrentDocuments[0].text='caller changed span';
await assert.rejects(blocked.refresh({documents:[],generationRef},{reauthorize}),{code:'ERR_INFERENCE_HISTORY_LIMIT'});
release();const stable=await pending;assert.equal(stable.spans,1);
const stableRows=await blocked.adapter().search({query:'query',top:1,generationRef},{reauthorize});
assert.equal(stableRows.candidates[0].span.end,'original span'.length);
