import { canonicalSemanticJson } from '../../../src/index/semantic/identity.js';
import assert from 'node:assert/strict';
import { buildCallDependencySummaries } from '../../../src/index/semantic/compiler-call-summaries.js';
import { advanceTraceContext } from '../../../src/semantic/trace-context.js';
const ref=localId=>({partitionId:'sy1:'+ 'a'.repeat(64),localId});
const channel=(from,to)=>({kind:'flowsTo',from:ref(from),to:ref(to)});
const declarations=[{declaration:ref(0),parameters:[ref(1)],returns:[ref(2)],span:[0,10],complete:true},
  {declaration:ref(3),parameters:[ref(4)],returns:[ref(5)],span:[11,30],complete:true}];
const call={occurrence:ref(6),targets:[ref(0)],arguments:[ref(7)],result:ref(8),span:[15,20],invocationKind:'call',hasSpread:false};
const documents=[{summaries:declarations,calls:[call],flowEdges:[channel(1,2),channel(4,7),channel(8,5)]}];
const result=buildCallDependencySummaries(documents);
assert.equal(result.converged,true);
assert.deepEqual([...result.functions.get(canonicalSemanticJson(ref(3))).dependencies],[0]);
const spread=buildCallDependencySummaries([{...documents[0],calls:[{...call,hasSpread:true}]}]);
assert.equal(spread.functions.get(canonicalSemanticJson(ref(3))).dependencies.size,0,'spread arity cannot fabricate positional input flow');
assert.equal(buildCallDependencySummaries(documents,{maxIterations:0}).converged,false);
const enter={kind:'argumentToParameter',callSite:ref(6),contextKey:'project-a'};
const stack=advanceTraceContext([],enter,'downstream').stack;
assert.equal(advanceTraceContext(stack,{...enter,kind:'returnToResult',callSite:ref(9)},'downstream').skip,true);
assert.equal(advanceTraceContext(stack,{...enter,kind:'returnToResult',contextKey:'project-b'},'downstream').skip,true);
assert.deepEqual(advanceTraceContext(stack,{...enter,kind:'returnToResult'},'downstream').stack,[]);
assert.equal(advanceTraceContext(stack,enter,'downstream',1).frontier,'call_context_budget');
const aborted=new AbortController();aborted.abort();assert.throws(()=>buildCallDependencySummaries(documents,{signal:aborted.signal}),/abort/i);
console.log('Call dependency summaries and balanced invocation contexts passed');
