import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { createRecoveryFixture } from '../../helpers/semantic-recovery.js';
import { collectFileSemanticFacts } from '../../../src/index/semantic/collect-file.js';
import { collectEmbeddedSemanticSources, collectEmbeddedSemanticOwnership, getSegmentSemanticContext } from '../../../src/index/semantic/embedded-source.js';
import { persistEmbeddedSemanticCacheEntries, relocateEmbeddedSemanticCacheEntries } from '../../../src/index/semantic/embedded-cache.js';
import { createSemanticFactsRef } from '../../../src/index/semantic/file-ref.js';
import { prepareTypeScriptSyntax } from '../../../src/lang/typescript/syntax-context.js';
import { persistSemanticCacheEntry } from '../../../src/index/build/incremental/semantic-cache.js';
import { prepareCachedSemanticPlan } from '../../../src/storage/sqlite/semantic/from-cache.js';
import { ARTIFACT_SURFACE_VERSION } from '../../../src/contracts/versioning.js';
import { createSemanticLspSession } from '../../../src/index/semantic/lsp-session.js';
import { createSemanticCompilerSession } from '../../../src/index/semantic/compiler-session.js';
const local = 'export const greeting: string = "hé😀";\r\nf(1,2,3,4,5,{items:[1,,3]});';
const text = '<script>' + local + '</script>';
const fixture = await createRecoveryFixture(text);
try {
  const policy = { languages: ['javascript','typescript'], storage: { batchRows: 11, batchBytes: 8192 }, enrichment: {} };
  const parent = await collectFileSemanticFacts({ ...fixture.options, bytes: fixture.bytes, text, language: 'vue', relPath: 'original.js', repositoryNamespace: fixture.root, policy });
  const storage = { generation: fixture.generation, relativePath: 'semantic' };
  const parentRef = createSemanticFactsRef({ source: parent.source, partitions: [parent.partition], syntaxPartitionId: parent.partition.partitionId, storage, coverage: parent.coverage });
  const segment = { start: 8, end: 8 + local.length, languageId: 'ts', segmentUid: 'fixture-segment' };
  const options = { parentFacts: parent, segments: [segment, segment], text, repositoryNamespace: fixture.root, stagingRoot: fixture.stagingRoot, storage, diskAccount: fixture.account, policy };
  const embedded = await collectEmbeddedSemanticSources(options); assert.equal(embedded.segmentFactsRefs.length, 1);
  const context = getSegmentSemanticContext(embedded.syntaxContexts, segment); assert.equal(context.typeScriptSyntaxContext.parses, 1);
  assert.equal(prepareTypeScriptSyntax(local, context).sourceFile, context.tsSyntax.sourceFile); assert.equal(context.typeScriptSyntaxContext.parses, 1); assert.equal(context.typeScriptSyntaxContext.reuses, 1);
  const owned = await collectEmbeddedSemanticOwnership({ ...options, embedded, chunks: [{ chunkUid: 'fixture-chunk', start: segment.start, end: segment.end, segment }] });
  assert.equal(owned.length, 1);
  const rows = []; const store = fixture.store(owned[0].factsRef.partitions);
  for (const partition of owned[0].factsRef.partitions) for await (const row of store.iterateRows(partition.partitionId, 'semantic_ownership')) rows.push(row);
  assert.ok(rows.length); assert.ok(rows.every(row => row.chunkUid === 'fixture-chunk'));
  const bundleDir = path.join(fixture.root, 'bundles'); await fs.mkdir(bundleDir);
  const entries = await persistEmbeddedSemanticCacheEntries({ entries: owned, repoRoot: fixture.root, bundleDir, buildRoot: fixture.root, dependencySignatures: { semantic: 'a'.repeat(64) }, diskAccount: fixture.account });
  const parentLocator = await persistSemanticCacheEntry({ factsRef: parentRef, repoRoot: fixture.root, bundleDir, buildRoot: fixture.root, dependencySignatures: { semantic: 'a'.repeat(64) }, diskAccount: fixture.account });
  const plan = await prepareCachedSemanticPlan({ repoRoot: fixture.root, incrementalData: { bundleDir, manifest: { artifactSurfaceVersion: ARTIFACT_SURFACE_VERSION, semanticEnabled: true, semanticGeneration: fixture.generation, semanticDependencySignatures: { semantic: 'a'.repeat(64) }, files: { 'original.js': { semanticCache: parentLocator, semanticSegmentCaches: entries } } } } });
  assert.equal(plan.entries.length, 2); assert.equal(plan.partitions.length, 3); assert.ok(plan.entries.some(entry => entry.file.includes('#semantic-segment:')));
  const targetBuildRoot = path.join(fixture.root, 'warm'); await fs.mkdir(targetBuildRoot);
  const relocated = await relocateEmbeddedSemanticCacheEntries({ entries, parentFacts: parentRef, parentBytes: fixture.bytes, repoRoot: fixture.root, bundleDir, dependencySignatures: { semantic: 'a'.repeat(64) }, targetBuildRoot, storage: { ...storage, generation: { baseBuildId: 'warm-build', semanticRevision: 0 } }, diskAccount: fixture.account });
  assert.deepEqual(relocated.semanticSegmentFactsRefs[0].factsRef.partitions.map(p => p.canonicalHash), owned[0].factsRef.partitions.map(p => p.canonicalHash)); assert.equal(relocated.semanticEvidenceArtifacts.length, 1);
  await assert.rejects(relocateEmbeddedSemanticCacheEntries({ entries, parentFacts: { ...parentRef, sourceHash: 'f'.repeat(64) }, parentBytes: fixture.bytes, repoRoot: fixture.root, bundleDir, dependencySignatures: { semantic: 'a'.repeat(64) }, targetBuildRoot, storage, diskAccount: fixture.account }), { code: 'ERR_SEMANTIC_CACHE_INTEGRITY' });
  const state = { semanticDiskAccount: fixture.account, chunks: [], semanticFactsByFile: new Map([['original.js',parentRef], ['original.js#semantic-segment:' + owned[0].factsRef.sourceUnitId, owned[0].factsRef]]) };
  const compiler = await createSemanticCompilerSession({ state, runtime: { root: fixture.root, buildRoot: fixture.root, semanticPolicy: policy } });
  const doc = { virtualPath: 'original.js.__segment.ts', containerPath: 'original.js', segmentUid: segment.segmentUid, segmentRange: { start: segment.start, end: segment.end }, text: local };
  const prepared = compiler.prepareDocuments([doc]); assert.equal(prepared.length, 1); assert.equal(prepared[0].semanticSourceUnitId, owned[0].factsRef.sourceUnitId);
  const ts = context.tsSyntax.ts; const group = compiler.beginGroup({ ts, program: { getSourceFiles: () => [context.tsSyntax.sourceFile], isSourceFileDefaultLibrary: () => false }, options: {}, documents: prepared }); assert.equal(group.mappedFiles.size, 1);
  const invalid = compiler.beginGroup({ ts, program: { getSourceFiles: () => [] }, options: {}, documents: [{ ...doc, text: local + ' ' }] }); assert.equal(invalid.mappedFiles.size, 0);
  const lsp = await createSemanticLspSession({ state, runtime: { root: fixture.root, buildRoot: fixture.root, semanticPolicy: policy } });
  const lspDoc = lsp.prepareDocuments([doc])[0]; const targets = await lsp.targetsForDocument(lspDoc); assert.ok(targets.length);
  let requested = 0; await lsp.collectDocument({ doc: lspDoc, uri: 'file:///fixture/segment.ts', targets, requestDefinition: async () => { requested++; return { attempted: true, payload: { uri: 'file:///fixture/segment.ts', range: { start: { line: 0, character: 13 }, end: { line: 0, character: 21 } } } }; } });
  assert.equal(requested, targets.length); const output = lsp.output(); assert.equal(output.partitions.length, 1);
  const analysisStore = fixture.store([...owned[0].factsRef.partitions,...output.partitions]); const bindings = []; for await (const row of analysisStore.iterateRows(output.partitions[0].partitionId,'semantic_records')) if(row.kind === 'binding') bindings.push(row);
  assert.ok(bindings.every(row => row.data.status === 'resolved'));
  state.semanticFactsByFile.set('original.js#semantic-segment:' + owned[0].factsRef.sourceUnitId, createSemanticFactsRef({ source: embedded.sourceFacts[0].facts.source, partitions: [...owned[0].factsRef.partitions,...output.partitions], syntaxPartitionId: owned[0].factsRef.syntaxPartitionId, storage, coverage: [] }));
  assert.equal((await lsp.targetsForDocument(lspDoc)).length, 0, 'refresh compiler/provider binding inventory before requesting unresolved positions');
  const synthetic = await collectEmbeddedSemanticSources({ ...options, segments: [{ ...segment, segmentUid: 'synthetic-segment', text: 'const replacement = 1;' }] }); assert.equal(synthetic.sourceFacts[0].facts.source.mapping.quality, 'synthetic');
  const syntheticOwnership = await collectEmbeddedSemanticOwnership({ ...options, embedded: synthetic, chunks: [{ chunkUid: 'fixture-chunk',start: segment.start,end:segment.end, segment: { ...segment,segmentUid:'synthetic-segment' } }] });
  assert.equal(syntheticOwnership[0].factsRef.counts.semantic_ownership, 0);
  console.log('embedded component parse reuse, ownership, cache relocation and compiler VFS mapping passed');
} finally { await fixture.cleanup(); }
