#!/usr/bin/env node
import fsPromises from 'node:fs/promises';
import path from 'node:path';
import { repoRoot } from '../helpers/root.js';

const root = repoRoot();
const commandsPath = path.join(root, 'docs', 'guides', 'commands.md');
const inventoryPath = path.join(root, 'docs', 'tooling', 'script-inventory.json');
const phaseDir = path.join(root, 'docs', 'phases', 'phase-3');

const fail = (message) => {
  console.error(`script inventory docs test failed: ${message}`);
  process.exit(1);
};

const readPhaseSpecs = async () => {
  try {
    const entries = await fsPromises.readdir(phaseDir, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
      .map((entry) => `docs/phases/phase-3/${entry.name}`)
      .sort();
  } catch {
    return [];
  }
};

const extractSection = (lines, header) => {
  const start = lines.indexOf(header);
  if (start === -1) fail(`missing section header: ${header}`);
  const items = [];
  for (let i = start + 1; i < lines.length; i += 1) {
    const line = lines[i];
    if (line.startsWith('## ')) break;
    if (!line.trim()) {
      if (items.length) break;
      continue;
    }
    if (line.startsWith('- ')) {
      items.push(line);
    } else if (items.length) {
      break;
    }
  }
  return items;
};

const assertSameList = (label, actual, expected) => {
  if (actual.length !== expected.length) {
    fail(`${label} length mismatch (expected ${expected.length}, got ${actual.length})`);
  }
  for (let i = 0; i < expected.length; i += 1) {
    if (actual[i] !== expected[i]) {
      fail(`${label} mismatch at line ${i + 1}: expected "${expected[i]}", got "${actual[i]}"`);
    }
  }
};

let commandsRaw;
let inventoryRaw;
try {
  [commandsRaw, inventoryRaw] = await Promise.all([
    fsPromises.readFile(commandsPath, 'utf8'),
    fsPromises.readFile(inventoryPath, 'utf8')
  ]);
} catch (error) {
  fail(error?.message || String(error));
}

const lines = commandsRaw.split(/\r?\n/);
if (!lines.includes('This file is generated by `node tools/script-inventory.js`.')) {
  fail('missing generator header');
}

const expectedPhaseSpecs = await readPhaseSpecs();
const actualPhaseSpecs = extractSection(lines, '## Phase 3 specs').map((line) => {
  const match = line.match(/`([^`]+)`/);
  return match ? match[1] : line.replace(/^-\s+/, '').trim();
});
assertSameList('Phase 3 specs', actualPhaseSpecs, expectedPhaseSpecs);

const expectedStableEntrypoints = [
  '- `npm test` (runs `tests/run.js`)',
  '- `npm run test:pr` (PR suite)',
  '- `npm run test:nightly` (nightly suite)',
  '- `npm run lint`',
  '- `npm run format`',
  '- `npm run config:budget`',
  '- `npm run env:check`',
  '- `npm run verify`'
];
const actualStableEntrypoints = extractSection(lines, '## Stable entrypoints');
assertSameList('Stable entrypoints', actualStableEntrypoints, expectedStableEntrypoints);

const preferLine = 'Prefer `pairofcleats search`, `pairofcleats index build`, and `pairofcleats index watch` for user-facing workflows.';
if (!lines.includes(preferLine)) {
  fail('missing preferred CLI entrypoints note');
}

let inventory;
try {
  inventory = JSON.parse(inventoryRaw);
} catch (error) {
  fail(`unable to parse script inventory: ${error?.message || error}`);
}
const inventoryNames = new Set((inventory.scripts || []).map((entry) => entry.name));

const tableStart = lines.indexOf('| Script | Category | CI Allowed | Replacement |');
if (tableStart === -1) fail('missing script table header');
const scriptNames = [];
for (let i = tableStart + 2; i < lines.length; i += 1) {
  const line = lines[i];
  if (!line.startsWith('|')) break;
  const match = line.match(/^\|\s+`([^`]+)`\s+\|/);
  if (match) scriptNames.push(match[1]);
}

const docSet = new Set(scriptNames);
const missing = Array.from(inventoryNames).filter((name) => !docSet.has(name));
const extra = Array.from(docSet).filter((name) => !inventoryNames.has(name));
if (missing.length || extra.length) {
  if (missing.length) console.error(`Missing in commands.md: ${missing.sort().join(', ')}`);
  if (extra.length) console.error(`Extra in commands.md: ${extra.sort().join(', ')}`);
  process.exit(1);
}

console.log('script inventory docs test passed');
