name: Auto-merge repository history and agent info

on:
  pull_request:
    branches: [main, master] # adjust to your target branches if needed
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Sync tools from master
        run: |
          git fetch origin master
          git checkout origin/master -- tools

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Compute merge-base
        id: mergebase
        run: |
          echo "MERGE_BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})" >> $GITHUB_ENV

      - name: Auto-merge metrics.json
        run: |
          bash tools/merge-metrics.sh \
            ${{ env.MERGE_BASE }} .repoMetrics/metrics.json .repoMetrics/metrics.json


      - name: Auto-merge searchHistory
        run: |
          bash tools/merge-history.sh \
            ${{ env.MERGE_BASE }} .repoMetrics/searchHistory .repoMetrics/searchHistory

      - name: Auto-merge noResultQueries
        run: |
          bash tools/merge-no-results.sh \
            ${{ env.MERGE_BASE }} .repoMetrics/noResultQueries .repoMetrics/noResultQueries

      - name: Auto-merge agentInfo index.md
        run: |
          bash tools/merge-agentinfo-index.sh \
            ${{ env.MERGE_BASE }} .agentInfo/index.md .agentInfo/index.md

      - name: Auto-merge agentInfo index-detailed.md
        run: |
          bash tools/merge-agentinfo-index.sh \
            ${{ env.MERGE_BASE }} .agentInfo/index-detailed.md .agentInfo/index-detailed.md

      - name: Auto-merge agentInfo notes
        run: |
          find .agentInfo/notes -name '*.md' -print0 | while IFS= read -r -d '' file; do
            bash tools/merge-agentinfo-notes.sh \
              ${{ env.MERGE_BASE }} "$file" "$file"
          done

      - name: Commit and push merged files
        run: |
          git add .repoMetrics/*.json
          git add .repoMetrics/searchHistory
          git add .repoMetrics/noResultQueries
          git add .agentInfo/index.md
          git add .agentInfo/index-detailed.md
          git add .agentInfo/notes/*.md

          git commit -m "Auto-merge repo metrics and agent info" || echo "Ay bruh"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
