/**
 * Widget config.
 *
 * ```json
 * {
 *   "name": "widget",
 *   "enabled": true
 * }
 * ```
 */
export function buildWidget() {
  // short
  // Longer inline comment that should be indexed by prose tokenization.
  /* Block comment that should be indexed as well. */
  // generated by lint
  console.log('ok');
  return true;
}

/* Copyright 2025 Example */
