import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import Database from 'better-sqlite3';
import { createRecoveryFixture, semanticBatch } from '../../helpers/semantic-recovery.js';
import { parseJavaScriptAst } from '../../../src/lang/javascript/parse.js';
import { createSemanticCollector } from '../../../src/index/semantic/javascript-collector.js';
import { createSemanticPartitionSink } from '../../../src/index/build/artifacts/writers/semantic/partition.js';
import { writeSemanticQueryIndex } from '../../../src/index/build/artifacts/writers/semantic/query-index.js';
import { createArtifactSemanticStore } from '../../../src/semantic/artifact-store.js';
import { createSqliteSemanticStore } from '../../../src/semantic/sqlite-store.js';
import { createSemanticDetailService } from '../../../src/semantic/detail.js';
import { createAnalysisPartitionId } from '../../../src/index/semantic/identity.js';
import { ARTIFACT_SURFACE_VERSION } from '../../../src/contracts/versioning.js';
import { SCHEMA_VERSION } from '../../../src/storage/sqlite/schema.js';
import { CREATE_SEMANTIC_TABLES_SQL } from '../../../src/storage/sqlite/semantic/schema.js';
import { writeSqliteIndexFormat } from '../../../src/storage/sqlite/index-format.js';
import { ingestSemanticPartition } from '../../../src/storage/sqlite/semantic/ingest.js';

const text = 'function work(input) { return call(1,2,3,4,5,{nested:[input,,...input], value:input}); }\r\nlarge(' + Array.from({ length: 300 }, (_, i) => i).join(',') + ');';
const fixture = await createRecoveryFixture(text);
let db;
try {
  const collector = createSemanticCollector({ ast: parseJavaScriptAst(text), source: fixture.source, partitionId: fixture.partitionId }, { batchRows: 128, batchBytes: 65536 });
  const sink = await createSemanticPartitionSink({ ...fixture.options, structuralSlots: collector.structuralSlots, batchRows: 128, batchBytes: 65536 });
  for (const batch of collector.batches) await sink.appendBatch(batch);
  const syntax = await sink.finalizeSource();
  const store = fixture.store([syntax]);
  const nodes = [];
  for await (const row of store.iterateRows(fixture.partitionId, 'semantic_records')) nodes.push(row);
  const call = nodes.find((row) => row.data.syntacticArgumentCount === 6);
  const large = nodes.find((row) => row.data.syntacticArgumentCount === 300);
  const ref = (localId) => ({ partitionId: fixture.partitionId, localId });
  const ownerId = createAnalysisPartitionId({ pass: { name: 'ownership', version: 'fixture' }, inputPartitionHashes: [syntax.canonicalHash], compilerContext: null, dependencySummaryHashes: [], analysisPolicy: {} });
  const ownerSink = await createSemanticPartitionSink({ ...fixture.options, partitionId: ownerId });
  await ownerSink.appendBatch(semanticBatch(ownerId, [
    { family: 'ownership', row: { recordRef: ref(call.id), chunkUid: 'chunk-work', role: 'primary' } },
    { family: 'ownership', row: { recordRef: ref(call.id), chunkUid: 'chunk-overlap', role: 'overlap' } }
  ]));
  const owner = await ownerSink.finalizeSource();
  const partitions = [syntax, owner];
  const base = fixture.store(partitions);
  const index = await writeSemanticQueryIndex({ root: fixture.stagingRoot, generation: fixture.generation, partitions, store: base, diskAccount: fixture.account, batchRows: 17, batchBytes: 8192, maxOpenRuns: 2 });
  assert.ok(index.pieces.length > 10, 'force multiple query parts and merge passes');
  const artifact = createArtifactSemanticStore({ root: fixture.stagingRoot, repoRoot: fixture.root, generation: fixture.generation, artifactSurfaceVersion: ARTIFACT_SURFACE_VERSION, partitions, queryIndex: index });
  const metrics = {};
  const targeted = await artifact.getRelatedPage(ref(call.id), 'semantic_operands', { limit: 128, metrics });
  assert.equal(targeted.rows.filter((row) => row.slot === 'argument').length, 6);
  assert.ok(metrics.rowsRead < 60, 'lookup reads logarithmic index rows and selected canonical rows, not the graph');
  const sixth = targeted.rows.find((row) => row.slot === 'argument' && row.ordinal === 5).child;
  const nested = await artifact.getRelatedPage(sixth, 'semantic_operands');
  assert.ok(nested.rows.length > 0, 'nested object members remain discoverable by child refs');
  assert.equal((await artifact.getRelatedPage(ref(call.id), 'semantic_ownership')).rows.length, 2);
  const callee = targeted.rows.find((row) => row.slot === 'callee').child;
  const request = { repoRoot: fixture.root, generation: fixture.generation, refs: [ref(call.id), ref(large.id), callee], include: ['operands', 'names', 'ownership'], limits: { records: 2, rows: 19, bytes: 8192 } };
  const drain = async (backend) => {
    const detail = createSemanticDetailService();
    let cursor = null, pages = 0;
    const aggregate = { records: [], operands: [], names: [], ownership: [] };
    do {
      const result = await detail({ store: backend, request: { ...request, cursor } });
      assert.ok(Buffer.byteLength(JSON.stringify(result)) <= request.limits.bytes);
      assert.ok(result.coverage.response.hydratedCount <= request.limits.rows);
      assert.ok(result.records.length <= request.limits.records);
      for (const field of Object.keys(aggregate)) aggregate[field].push(...result[field]);
      cursor = result.cursor;
      assert.ok(++pages < 60, 'continuations make progress');
    } while (cursor);
    return aggregate;
  };
  const artifactResult = await drain(artifact);
  assert.equal(artifactResult.operands.filter((row) => row.parent.localId === large.id && row.slot === 'argument').length, 300);
  assert.ok(artifactResult.names.some((row) => row.value === 'call'));
  assert.ok(artifactResult.records.some((row) => row.kind === 'occurrence' && row.data.expression.localId === callee.localId));
  db = new Database(':memory:');
  db.pragma('user_version = ' + SCHEMA_VERSION); db.exec(CREATE_SEMANTIC_TABLES_SQL); writeSqliteIndexFormat(db);
  db.exec('BEGIN');
  for (const descriptor of partitions) await ingestSemanticPartition({ db, store: base, descriptor });
  db.exec('COMMIT');
  db.prepare('INSERT INTO index_format_meta(key,value) VALUES (?,?)').run('semanticGeneration', JSON.stringify(fixture.generation));
  const sqlite = createSqliteSemanticStore({ db, repoRoot: fixture.root, indexPath: ':memory:', generation: fixture.generation, artifactSurfaceVersion: ARTIFACT_SURFACE_VERSION });
  assert.deepEqual(await drain(sqlite), artifactResult, 'artifact/SQLite ordered hydration parity');
  const limited = createSemanticDetailService({ maxRows: 5 });
  await assert.rejects(limited({ store: artifact, request }), { code: 'ERR_SEMANTIC_QUERY_LIMIT' });
  const service = createSemanticDetailService();
  const page = await service({ store: artifact, request });
  await assert.rejects(service({ store: artifact, request: { ...request, include: ['operands'], cursor: page.cursor } }), { code: 'ERR_SEMANTIC_CURSOR_EXPIRED' });
  await assert.rejects(service({ store: sqlite, request: { ...request, cursor: page.cursor } }), { code: 'ERR_SEMANTIC_CURSOR_EXPIRED' });
  await assert.rejects(service({ store: artifact, request: { ...request, generation: { ...fixture.generation, baseBuildId: 'other' } } }), { code: 'ERR_SEMANTIC_GENERATION_MISMATCH' });
  await assert.rejects(service({ store: artifact, request: { ...request, repoRoot: 'other' } }), { code: 'ERR_SEMANTIC_SCOPE_MISMATCH' });
  const controller = new AbortController(); controller.abort();
  await assert.rejects(service({ store: artifact, request, signal: controller.signal }), /abort/i);
  const expired = createSemanticDetailService({ ttlMs: 1 });
  const old = await expired({ store: artifact, request });
  await new Promise((resolve) => setTimeout(resolve, 3));
  await assert.rejects(expired({ store: artifact, request: { ...request, cursor: old.cursor } }), { code: 'ERR_SEMANTIC_CURSOR_EXPIRED' });
  const piece = index.pieces[0];
  await fs.appendFile(path.join(fixture.stagingRoot, piece.path), ' ');
  await assert.rejects(artifact.getRelatedPage(ref(call.id), 'semantic_operands').then(() => artifact.getRelatedPage(ref(0), 'semantic_lookup')));
  console.log('Semantic indexed detail hydration parity passed');
} finally { if (db) db.close(); await fixture.cleanup(); }
