export const buildInventoryReportMarkdown = (inventory) => {
  const mdLines = [];
  mdLines.push('# Config Inventory');
  mdLines.push('');
  mdLines.push(`Generated: ${inventory.generatedAt}`);
  mdLines.push('');
  mdLines.push('This file is generated by `node tools/config-inventory.js`.');
  mdLines.push('See `docs/config-inventory-notes.md` for ownership and overlap analysis.');
  mdLines.push('');
  mdLines.push('## Summary');
  mdLines.push(`- Config keys: ${inventory.configSchema.totalKeys}`);
  mdLines.push(`- Config leaf keys: ${inventory.configSchema.leafKeys}`);
  mdLines.push(`- Public config keys: ${inventory.configKeysPublic.length}`);
  mdLines.push(`- Env vars: ${inventory.envVars.length}`);
  mdLines.push(`- Public env vars: ${inventory.envVarsPublic.length}`);
  mdLines.push(`- CLI flags: ${inventory.cliFlags.totalFlags}`);
  mdLines.push(`- Public CLI flags: ${inventory.cliFlags.publicFlags.length}`);
  mdLines.push('');
  mdLines.push('## Allowlist drift');
  mdLines.push('');
  mdLines.push(`- Unknown config keys: ${inventory.configKeysUnknown.length}`);
  mdLines.push(`- Unknown env vars: ${inventory.envVarsUnknown.length}`);
  mdLines.push(`- Unknown public CLI flags: ${inventory.cliFlags.publicUnknown.length}`);
  mdLines.push('');
  mdLines.push('## Config keys by top-level namespace');
  mdLines.push('');
  for (const entry of inventory.configSchema.topLevel) {
    mdLines.push(`- ${entry.key}: ${entry.count}`);
  }
  mdLines.push('');
  mdLines.push('## Env vars');
  mdLines.push('');
  if (inventory.envVars.length === 0) {
    mdLines.push('- (none)');
  } else {
    for (const entry of inventory.envVars) {
      mdLines.push(`- ${entry.name} (${entry.files.length} files)`);
    }
  }
  mdLines.push('');
  mdLines.push('## Public CLI flags');
  mdLines.push('');
  mdLines.push(inventory.cliFlags.publicFlags.length
    ? inventory.cliFlags.publicFlags.join(', ')
    : '(none)');
  mdLines.push('');
  mdLines.push('## Internal CLI flags');
  mdLines.push('');
  mdLines.push(inventory.cliFlags.internalFlags.length
    ? inventory.cliFlags.internalFlags.join(', ')
    : '(none)');
  mdLines.push('');
  mdLines.push('## CLI flags (duplicated across files)');
  mdLines.push('');
  if (inventory.cliFlags.duplicated.length === 0) {
    mdLines.push('- (none)');
  } else {
    for (const entry of inventory.cliFlags.duplicated) {
      mdLines.push(`- ${entry.flag} (${entry.count} files)`);
    }
  }
  mdLines.push('');
  mdLines.push('## CLI flags by file');
  mdLines.push('');
  for (const entry of inventory.cliFlags.byFile) {
    mdLines.push(`### ${entry.file}`);
    mdLines.push('');
    mdLines.push(entry.flags.length ? entry.flags.join(', ') : '(none)');
    mdLines.push('');
  }
  mdLines.push('## Config keys (full list)');
  mdLines.push('');
  mdLines.push('```');
  for (const entry of inventory.configKeys) {
    const type = entry.type ? ` (${entry.type})` : '';
    const enumValues = entry.enum && entry.enum.length ? ` enum=${entry.enum.join('|')}` : '';
    mdLines.push(`${entry.path}${type}${enumValues}`.trim());
  }
  mdLines.push('```');
  mdLines.push('');
  if (inventory.cliFlags.dynamicOptionFiles.length) {
    mdLines.push('## Notes');
    mdLines.push('');
    mdLines.push('Dynamic CLI options detected in these files; verify flags manually:');
    mdLines.push('');
    for (const file of inventory.cliFlags.dynamicOptionFiles) {
      mdLines.push(`- ${file}`);
    }
    mdLines.push('');
  }
  return mdLines.join('\n');
};
