import { loadSearchIndexes } from '../load-indexes.js';

/**
 * Load search indexes with startup stage tracking and abort guard.
 *
 * @param {{
 *   stageTracker:object,
 *   throwIfAborted:()=>void,
 *   rootDir:string,
 *   userConfig:object,
 *   searchMode:string,
 *   runProse:boolean,
 *   runExtractedProse:boolean,
 *   runCode:boolean,
 *   runRecords:boolean,
 *   useSqlite:boolean,
 *   useLmdb:boolean,
 *   emitOutput:boolean,
 *   exitOnError:boolean,
 *   annActive:boolean,
 *   filtersActive:boolean,
 *   chunkAuthorFilterActive:boolean,
 *   contextExpansionEnabled:boolean,
 *   graphRankingEnabled:boolean,
 *   sqliteFtsEnabled:boolean,
 *   backendLabel:string,
 *   backendForcedTantivy:boolean,
 *   indexCache:object|null,
 *   modelIdDefault:string,
 *   fileChargramN:number,
 *   hnswConfig:object,
 *   lancedbConfig:object,
 *   tantivyConfig:object,
 *   strictIndexMetaByMode:Map<string, boolean>,
 *   indexStates:object,
 *   strict:boolean,
 *   loadIndexFromSqlite:(...args:any[])=>Promise<any>,
 *   loadIndexFromLmdb:(...args:any[])=>Promise<any>,
 *   resolvedDenseVectorMode:string|null,
 *   joinComments:boolean,
 *   allowUnsafeMix:boolean,
 *   requiredArtifacts:object,
 *   asOfContext:object|null
 * }} input
 * @returns {Promise<any>}
 */
export const loadRunSearchIndexesWithTracking = async ({
  stageTracker,
  throwIfAborted,
  rootDir,
  userConfig,
  searchMode,
  runProse,
  runExtractedProse,
  runCode,
  runRecords,
  useSqlite,
  useLmdb,
  emitOutput,
  exitOnError,
  annActive,
  filtersActive,
  chunkAuthorFilterActive,
  contextExpansionEnabled,
  graphRankingEnabled,
  sqliteFtsEnabled,
  backendLabel,
  backendForcedTantivy,
  indexCache,
  modelIdDefault,
  fileChargramN,
  hnswConfig,
  lancedbConfig,
  tantivyConfig,
  strictIndexMetaByMode,
  indexStates,
  strict,
  loadIndexFromSqlite,
  loadIndexFromLmdb,
  resolvedDenseVectorMode,
  joinComments,
  allowUnsafeMix,
  requiredArtifacts,
  asOfContext
}) => {
  const indexesStart = stageTracker.mark();
  const loaded = await loadSearchIndexes({
    rootDir,
    userConfig,
    searchMode,
    runProse,
    runExtractedProse,
    runCode,
    runRecords,
    useSqlite,
    useLmdb,
    emitOutput,
    exitOnError,
    annActive,
    filtersActive,
    chunkAuthorFilterActive,
    contextExpansionEnabled,
    graphRankingEnabled,
    sqliteFtsRequested: sqliteFtsEnabled,
    backendLabel,
    backendForcedTantivy,
    indexCache,
    modelIdDefault,
    fileChargramN,
    hnswConfig,
    lancedbConfig,
    tantivyConfig,
    indexMetaByMode: strictIndexMetaByMode,
    indexStates,
    strict,
    loadIndexFromSqlite,
    loadIndexFromLmdb,
    resolvedDenseVectorMode,
    loadExtractedProse: joinComments,
    allowUnsafeMix,
    requiredArtifacts,
    indexDirByMode: asOfContext?.strict ? asOfContext.indexDirByMode : null,
    indexBaseRootByMode: asOfContext?.strict ? asOfContext.indexBaseRootByMode : null,
    explicitRef: asOfContext?.strict === true
  });
  stageTracker.record('startup.indexes', indexesStart, { mode: 'all' });
  throwIfAborted();
  return loaded;
};
