/**
 * Build normalized query-plan input payload consumed by dictionary/planning.
 *
 * @param {{
 *   postingsConfig:object,
 *   caseTokens:boolean,
 *   fileFilter:string|null,
 *   caseFile:boolean,
 *   searchRegexConfig:object|null,
 *   filePrefilterEnabled:boolean,
 *   fileChargramN:number,
 *   searchType:boolean,
 *   searchAuthor:boolean,
 *   searchImport:boolean,
 *   chunkAuthorFilter:any,
 *   branchesMin:number|null,
 *   loopsMin:number|null,
 *   breaksMin:number|null,
 *   continuesMin:number|null,
 *   churnMin:number|null,
 *   extFilter:any,
 *   langFilter:any,
 *   extImpossible:boolean,
 *   langImpossible:boolean,
 *   metaFilters:any,
 *   modifiedAfter:string|null,
 *   modifiedSinceDays:number|null,
 *   fieldWeightsConfig:object|null,
 *   denseVectorMode:string|null,
 *   branchFilter:string|null
 * }} input
 * @returns {object}
 */
export const buildQueryPlanInput = ({
  postingsConfig,
  caseTokens,
  fileFilter,
  caseFile,
  searchRegexConfig,
  filePrefilterEnabled,
  fileChargramN,
  searchType,
  searchAuthor,
  searchImport,
  chunkAuthorFilter,
  branchesMin,
  loopsMin,
  breaksMin,
  continuesMin,
  churnMin,
  extFilter,
  langFilter,
  extImpossible,
  langImpossible,
  metaFilters,
  modifiedAfter,
  modifiedSinceDays,
  fieldWeightsConfig,
  denseVectorMode,
  branchFilter
}) => ({
  postingsConfig,
  caseTokens,
  fileFilter,
  caseFile,
  searchRegexConfig,
  filePrefilterEnabled,
  fileChargramN,
  searchType,
  searchAuthor,
  searchImport,
  chunkAuthorFilter,
  branchesMin,
  loopsMin,
  breaksMin,
  continuesMin,
  churnMin,
  extFilter,
  langFilter,
  extImpossible,
  langImpossible,
  metaFilters,
  modifiedAfter,
  modifiedSinceDays,
  fieldWeightsConfig,
  denseVectorMode,
  branchFilter
});
