import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { buildDependencySignatures, buildIncrementalSignature } from '../../../src/index/build/indexer/signatures.js';
import { loadIncrementalState } from '../../../src/index/build/incremental/planning.js';
const base = { languageOptions:{},indexingConfig:{artifacts:{format:'json'}},embeddingEnabled:true,
  embeddingBatchSize:8,embeddingIdentityKey:'model-a',gitBlameEnabled:false,repoProvenance:{provider:'git',head:{commitId:'a'}},profile:{id:'default'} };
const deps = runtime => buildDependencySignatures(runtime,'code','tokens');
const signature = runtime => buildIncrementalSignature(runtime,'code','tokens');
const batch = {...base,embeddingBatchSize:64,threadLimits:{fileConcurrency:12}};
assert.deepEqual(deps(batch),deps(base));
assert.equal(signature(batch),signature(base));
const output = {...base,indexingConfig:{artifacts:{format:'jsonl'}}};
assert.equal(signature(output),signature(base));
assert.notEqual(deps(output).artifacts,deps(base).artifacts);
assert.equal(signature({...base,repoProvenance:{provider:'git',head:{commitId:'b'}}}),signature(base));
assert.notEqual(deps({...base,embeddingIdentityKey:'model-b'}).embeddings,deps(base).embeddings);
assert.equal(deps({...base,languageOptions:{javascript:{parser:'babel'}}}).lexical,deps(base).lexical);
assert.notEqual(deps({...base,languageOptions:{javascript:{parser:'babel'}}}).parse,deps(base).parse);
const parent=process.env.PAIROFCLEATS_DEPENDENCY_TEST_DIR||path.resolve('temp/tasks/retrieval-dependencies');
await fs.mkdir(parent,{recursive:true});
const root=await fs.mkdtemp(path.join(parent,'manifest-'));
const state=await loadIncrementalState({repoCacheRoot:root,mode:'code',enabled:true,cacheSignature:signature(base),tokenizationKey:'tokens',dependencySignatures:deps(base)});
state.manifest.files={'src/a.js':{hash:'fixture',size:4,mtimeMs:123,bundle:'retained.json'}};
await fs.writeFile(state.manifestPath,JSON.stringify(state.manifest));
const same=await loadIncrementalState({repoCacheRoot:root,mode:'code',enabled:true,cacheSignature:signature(batch),tokenizationKey:'tokens',dependencySignatures:deps(batch)});
assert.deepEqual(same.manifest.files,state.manifest.files);
assert.equal(same.artifactNeedsRebuild,false);
const changed=await loadIncrementalState({repoCacheRoot:root,mode:'code',enabled:true,cacheSignature:signature(output),tokenizationKey:'tokens',dependencySignatures:deps(output)});
assert.deepEqual(changed.manifest.files,state.manifest.files,'output change must preserve per-file bundles');
assert.equal(changed.artifactNeedsRebuild,true,'output change must prevent whole-index reuse');
assert.deepEqual(changed.manifest.dependencySignatures,deps(output));
console.log('Scheduling/batch/HEAD-only identities retain bundles; output-only changes rebuild artifacts without resetting file cache');
