import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { reuseCachedBundle } from '../../../src/index/build/file-processor/cached-bundle.js';
import { sha1 } from '../../../src/shared/hash.js';
import { loadIncrementalState, shouldReuseIncrementalIndex } from '../../../src/index/build/incremental/planning.js';
import { loadCachedBundleForFile, writeBundleForFile } from '../../../src/index/build/file-processor/incremental.js';
import { captureChunkingCheckpoint, resolveChunkingCheckpoint, resolveStageRefresh, preloadParseCheckpoints } from '../../../src/index/build/incremental/stage-reuse.js';
const parent = process.env.PAIROFCLEATS_DEPENDENCY_TEST_DIR || path.resolve('temp/tasks/retrieval-dependencies');
await fs.mkdir(parent, { recursive: true });
const root = await fs.mkdtemp(path.join(parent, 'stage-checkpoint-'));
const abs = path.join(root, 'source.js');
const text = 'function alpha() { return 1; }\n';
await fs.writeFile(abs, text);
const stat = await fs.stat(abs);
const old = {parse:'p1',lexical:'l1',enrichment:'e1',embeddings:'v1',artifacts:'a1'};
const load = dependencySignatures => loadIncrementalState({repoCacheRoot:root,mode:'code',enabled:true,tokenizationKey:dependencySignatures.lexical,cacheSignature:JSON.stringify(dependencySignatures),dependencySignatures});
const state = await load(old);
const chunks = [{start:0,end:text.length,meta:{name:'alpha'}}];
const checkpoint = captureChunkingCheckpoint(chunks, {usedHeuristicCodeChunking:false}, text.length);
assert.ok(checkpoint);
assert.equal(captureChunkingCheckpoint([{start:0,end:1,cycle: (()=>{const v={};v.self=v;return v;})()}],{},1),null,'unsupported optional checkpoint must not break a fresh build');
state.manifest.files['source.js'] = await writeBundleForFile({runIo:fn=>fn(),incrementalState:state,relKey:'source.js',fileStat:stat,fileHash:sha1(Buffer.from(text)),fileChunks:[{...chunks[0],tokens:['alpha'],seq:['alpha'],embedding:[1,2]}],parseCheckpoint:checkpoint,fileRelations:{imports:[]}});
await fs.writeFile(state.manifestPath,JSON.stringify(state.manifest));
for (const stage of ['lexical','enrichment','embeddings']) {
  const current = {...old,[stage]:'changed'};
  const refreshed = await load(current);
  assert.ok(refreshed.manifest.files['source.js'],'derived changes retain source bundle');
  assert.equal(refreshed.artifactNeedsRebuild,true);
  const loaded = await loadCachedBundleForFile({runIo:fn=>fn(),incrementalState:refreshed,absPath:abs,relKey:'source.js',fileStat:stat});
  assert.deepEqual(loaded.cachedBundle.stageRefresh,{parse:false,lexical:stage==='lexical',enrichment:stage==='enrichment',embeddings:stage==='embeddings'});
  const eligible = await preloadParseCheckpoints({entries:[{abs,rel:'source.js',stat}],incrementalState:refreshed});
  assert.equal(eligible.has(abs),true);
  assert.equal((await preloadParseCheckpoints({entries:[{abs,rel:'source.js',stat}],incrementalState:refreshed,maxBytes:1})).size,0);
}
const native = { start:0,end:text.length,chunkUid:'u1',virtualPath:'source.js',metaV2:{chunkId:'c1',chunkUid:'u1',virtualPath:'source.js',modifiers:[]},embedding:[1,2],embed_doc:[3,4],embed_code:[5,6],tokens:['alpha'],seq:['alpha'] };
const vectorRefresh=reuseCachedBundle({abs,relKey:'source.js',fileIndex:0,fileStat:stat,fileHash:sha1(Buffer.from(text)),ext:'.js',fileCaps:{},cachedBundle:{chunks:[native],fileRelations:{imports:[]},vfsManifestRows:[],stageRefresh:{embeddings:true}},incrementalState:state,fileStart:Date.now(),analysisPolicy:{metadata:{enabled:true}},mode:'code'});
assert.ok(vectorRefresh.result,JSON.stringify(vectorRefresh));
for(const key of ['embedding','embed_doc','embed_code']) assert.deepEqual(vectorRefresh.result.chunks[0][key],[]);
assert.deepEqual(native.embedding,[1,2],'invalidate returned vectors without mutating stored input');
assert.deepEqual(vectorRefresh.result.chunks[0].tokens,['alpha'],'vector changes preserve lexical payload');
const next={...old,enrichment:'e2'};
const interrupted = await load(next);
await fs.writeFile(interrupted.manifestPath,JSON.stringify(interrupted.manifest));
const resumed = await load(next);
assert.equal(resolveStageRefresh(next,resumed.manifest.files['source.js'].dependencySignatures).enrichment,true,'manifest-wide checkpoint must not mark untouched file current');
const reasons=[];
assert.equal(await shouldReuseIncrementalIndex({outDir:root,entries:[{rel:'source.js',stat}],manifest:resumed.manifest,log:m=>reasons.push(m),explain:true}),false);
assert.match(reasons[0],/per-file dependencies changed/,'interrupted refresh must also reject whole-index reuse');
assert.deepEqual((await load({...next,parse:'p2'})).manifest.files,{});
let calls=0;
const chunker=async()=>{calls++;return {chunks:[],chunkingDiagnostics:{}};};
const reused=await resolveChunkingCheckpoint({cached:checkpoint,textLength:text.length,chunker,input:{}});
assert.equal(calls,0);
reused.chunks[0].meta.name='mutated';
assert.equal(checkpoint.chunks[0].meta.name,'alpha');
await resolveChunkingCheckpoint({cached:checkpoint,textLength:1,chunker,input:{}});
assert.equal(calls,1);
await fs.writeFile(abs,'changed source\n');
const changedStat=await fs.stat(abs);
assert.equal((await preloadParseCheckpoints({entries:[{abs,rel:'source.js',stat:changedStat}],incrementalState:resumed})).size,0,'changed sources must use normal parsing');
console.log('stage refresh: per-file dependencies, interrupted resume, persisted parse geometry, bounded admission and changed-source rejection passed');
