import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { applyTestEnv } from '../../helpers/test-env.js';
import { getRepoId } from '../../../tools/shared/dict-utils.js';
import { runNode } from '../../helpers/run-node.js';
import { readBundleFile } from '../../../src/shared/bundle-io.js';
const parent=process.env.PAIROFCLEATS_DEPENDENCY_TEST_DIR||path.resolve('temp/tasks/retrieval-dependencies');
await fs.mkdir(parent,{recursive:true});
const root=await fs.mkdtemp(path.join(parent,'stage-build-'));
const repo=path.join(root,'repo');
const cache=path.join(root,'cache');
await fs.mkdir(repo,{recursive:true});
await fs.writeFile(path.join(repo,'source.js'),'function alpha(value) { return value + 1; }\n');
const build=phrases=>{
  const env=applyTestEnv({cacheRoot:cache,embeddings:'stub',testConfig:{indexing:{scm:{provider:'none'},typeInference:false,typeInferenceCrossFile:false,riskAnalysis:false,riskAnalysisCrossFile:false,postings:{enablePhraseNgrams:phrases}},tooling:{autoEnableOnDetect:false,lsp:{enabled:false}}},extraEnv:{PAIROFCLEATS_WORKER_POOL:'off'}});
  const result=runNode([path.resolve('build_index.js'),'--stub-embeddings','--scm-provider','none','--incremental','--stage','stage2','--mode','code','--repo',repo],'stage refresh integration',repo,env,{stdio:'inherit',allowFailure:true});
  assert.equal(result.status,0);
};
const dir=path.join(cache,'repos',getRepoId(repo),'incremental','code');
const read=async()=>{
  const manifest=JSON.parse(await fs.readFile(path.join(dir,'manifest.json'),'utf8'));
  const entry=manifest.files['source.js'];
  assert.ok(entry,'source entry exists');
  const loaded=await readBundleFile(path.join(dir,'files',entry.bundles[0]),{format:entry.bundleFormat});
  assert.equal(loaded.ok,true);
  const bundle=loaded.bundle;
  return {manifest,entry,bundle};
};
build(false);
const first=await read();
assert.ok(first.bundle.parseCheckpoint,'actual parser creates reusable geometry');
build(true);
const second=await read();
assert.equal(first.entry.dependencySignatures.parse,second.entry.dependencySignatures.parse);
assert.notEqual(first.entry.dependencySignatures.lexical,second.entry.dependencySignatures.lexical);
assert.deepEqual(second.entry.dependencySignatures,second.manifest.dependencySignatures);
assert.deepEqual(first.bundle.parseCheckpoint,second.bundle.parseCheckpoint);
console.log('actual incremental builds preserve parser geometry and refresh lexical tags');
